name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      working-directory: react-app
      run: npm ci
    - name: Run Automated Tests
      working-directory: react-app
      run: npm run test

